# Generated by Django 4.2 on 2024-02-16 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_uuid',
            field=models.UUIDField(default=uuid.UUID('fffaaeb2-8b59-4a2b-9a43-c9151c3f46b2'), unique=True, verbose_name='UUID'),
        ),
    ]
