[tool.poetry]
name = "catalog-2-0"
version = "0.1.0"
description = ""
authors = ["HAN <han82@mail.ru>"]
readme = "README.md"
packages = [{include = "catalog_2"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
